apiVersion: exampleservice.ansible.com/v1alpha1
kind: ExampleService
metadata:
  labels:
    app.kubernetes.io/name: aap-example-service-operator
    app.kubernetes.io/managed-by: kustomize
  name: exampleservice-sample
spec:
  # TODO(user): Add fields here
